# BountyNet — Architecture & Implementation Spec

---

## Table of Contents

1. [Glossary](#1-glossary)
2. [Core Components](#2-core-components)
3. [Wallet Strategy](#3-wallet-strategy)
4. [Implementation](#4-implementation)
   - [Rust-to-Node Bridge (Dynamic Headless Identity)](#41-rust-to-node-bridge-dynamic-headless-identity)
   - [Solidity Escrow Contract (Circle Settlement)](#42-solidity-escrow-contract-circle-settlement)
5. [Pricing & Barter Economics](#5-pricing--barter-economics)
6. [Sleeve CLI UI](#6-sleeve-cli-ui)
7. [Stack Summary](#7-stack-summary)
8. [Repo Notes](#8-repo-notes)

---

## 1. Glossary

### The Economy

**Compute Credits**
The fungible, liquid unit of exchange in the BountyNet UI. Represents pre-paid LLM inference power (e.g., Anthropic API calls). While the smart contracts settle in USDC, the Solver's terminal displays earnings as Compute Credits — the fuel they have earned to run future autonomous tasks.

**Resource Claim (NFT)**
A non-fungible, cryptographic wrapper representing verified but not-yet-utilized infrastructure (e.g., a 50GB S3 bucket, a temporary Redis instance).

**Active Lease**
A Resource Claim that has been won by a Solver and is currently injected into their local `sleeve` environment as active credentials (`AWS_ACCESS_KEY_ID`, etc.).

---

### The Actors

**The Staker (Requester)**
The human developer or repository owner who pushes code. When their CI breaks, they stake USDC and/or Resource Claims into the Escrow Contract to incentivize a fix.

**The Solver (Agent)**
The autonomous reasoning loop (e.g., a local Claude or Wake instance) running on a bystander's machine. It ingests the broken environment, generates patches, tests them locally, and submits the winning PR.

**The Paymaster (Platform)**
The platform infrastructure. Provides gasless transaction routing and acts as broker between the staked USDC and the Anthropic API.

---

### The Infrastructure

**Context Payload (The Contract of Work)**
The deterministic, serialized artifact generated by `sleeve` when a build fails. Includes the exact toolchain versions (`.sleeve-agent.toml`), the specific source files, the error stack trace, and the exact terminal command required to verify the fix.

**Agent Identity (Headless Wallet)**
The `0x` address generated silently by the Dynamic Node SDK. Tied deterministically to a Solver's hardware machine ID — a "birth certificate" for the agent that requires no wallet setup from the human bystander.

**Inference Proxy**
The centralized Node.js gateway managed by the platform. Intercepts LLM requests from Solvers, verifies they are working on an active bounty, executes the prompt using the platform's master Anthropic key, and deducts the cost from the Staker's escrowed funds.

**Proof of Intent**
A lightweight signature proving a specific Agent Identity has formally locked onto a specific Context Payload. Required by the Inference Proxy to prevent agents from draining Compute Credits for non-bounty-related tasks.

**The CI Oracle (Webhook Verifier)**
The ultimate arbiter of truth. A lightweight service that listens to GitHub Webhooks. When the original repository's CI pipeline reports that a Solver's submitted patch has turned tests green, the Oracle signs the transaction that unlocks the Escrow Contract.

---

### The Alignment Check

Each layer of the stack maps cleanly to a single responsibility:

| Responsibility              | Owner           |
|-----------------------------|-----------------|
| Build the Context Payload   | `sleeve`        |
| Mint the Agent Identity     | Dynamic         |
| Handle Escrow & Settlement  | Circle          |
| Execute inference & bill    | Inference Proxy |

---

## 2. Core Components

### 2.1 Proof of Outcome — CI-to-Chain Oracle

The most critical missing piece is the **Trust Anchor**: a way for a GitHub Action to prove to a smart contract that a test passed, so funds can be released.

**What to scaffold:** A tiny Webhook Verifier (Node.js or Rust).

**Flow:**
1. PR build goes green → GitHub sends a signed webhook.
2. Verifier validates the GitHub signature.
3. Verifier checks that the PR originated from a registered BountyNet Solver.
4. Verifier calls `releaseReward()` on the Escrow Contract.

> Without this, payment is manual — which kills the autonomous agent narrative.

---

### 2.2 Resource Claim NFT / Voucher System

To support the **Barter Mesh** (agents trading S3 buckets, Redis instances, etc.), a standardized asset wrapper is required.

**What to scaffold:** An ERC-721 or ERC-1155 factory on Base Sepolia.

**Flow:**
- Staker offers "50GB S3 for 24h" → contract mints a Resource Claim token.
- Solver who wins the bounty receives this NFT.
- `sleeve claim <token-id>` sends the NFT (or an ownership signature) to the Resource Proxy.
- Resource Proxy returns temporary credentials, creating an Active Lease.

---

### 2.3 Inference Proxy — On-Chain OpenRouter Equivalent

A **Token-Gated API Gateway** specialized for Proof-of-Bounty.

**Logic:**
- Instead of a standard API key, the proxy accepts `Agent Identity + Active Bounty ID`.
- Requires a valid **Proof of Intent** signature before accepting any request.
- A **Token Estimator** middleware counts tokens used by the Solver and subtracts them from the Compute Stake deposited by the Staker.
- This prevents a $500 bill appearing for a $5 bounty.

---

### 2.4 GitHub App — Onboarding Surface

Stakers should not have to configure `sleeve` manually.

**What to scaffold:** A BountyNet GitHub App.

**Flow:**
1. Staker installs the app on their repo.
2. App automatically adds a `bounty.yml` GitHub Action.
3. This action triggers `sleeve bounty create` whenever:
   - A `fix-me` label is added to an issue, or
   - A test fails on `main`.

---

### 2.5 Bounty Feed

Solvers need a way to discover available work.

A `sleeve bounty list` command fetching active Context Payload hashes from the smart contract completes the marketplace feel — deployable as a web or mobile app.

---

### 2.6 SimBountyNet

A simulation layer to showcase platform activity.

- **Stakers:** GitHub repo owners (real or simulated).
- **Solvers:** Fake/LLM agents that simulate solving bounties to demonstrate activity for judges and demos.

---

## 3. Wallet Strategy

Use **Dynamic** for identity/onboarding and **Circle** for programmable infrastructure and settlement. They serve two distinct, complementary purposes.

### 3.1 Dynamic — Headless Identity

Dynamic is the entry point for zero-friction Solver onboarding.

- **UI Role:** When a bystander runs `sleeve join`, Dynamic generates a unique User ID (the Agent Identity) tied to their machine or GitHub identity.
- **Tech Role:** Dynamic provides the Auth Token the CLI uses to prove to the Inference Proxy that a specific agent is authorized to request Compute Credits.
- **Prize Target:** Dynamic `$1,667` Node SDK bounty.

### 3.2 Circle — Programmable Wallets

Once Dynamic identifies the user, Circle Developer-Controlled Wallets handle the actual assets.

- **UI Role:** Powers the `sleeve wallet` dashboard — tracks USDC balance, Compute Credits, and Resource Claim NFTs.
- **Tech Role:** Circle Programmable Wallets allow the Solver agent to sign nanopayments or swap transactions (via Uniswap) without the user seeing a private key or a confirmation popup.
- **Prize Target:** Circle `$6,000` Agentic Economy Nanopayments + `$4,000` Programmable Wallets.

---

## 4. Implementation

### 4.1 Rust-to-Node Bridge (Dynamic Headless Identity)

`sleeve` is written in Rust; the Dynamic Node SDK is the fastest path to generating non-custodial Agent Identities without a browser. Use `src/cmd.rs` to execute an embedded Node script.

#### Node Bridge Script

`src/assets/agent-sandbox/dynamic_init.mjs`

```js
import { createDynamicClient } from '@dynamic-labs/sdk-node';

const environmentId = process.env.DYNAMIC_ENVIRONMENT_ID;
const machineId = process.argv[2]; // Passed from Rust

const dynamicClient = createDynamicClient({ environmentId });

async function initAgent() {
  const user = await dynamicClient.users.createOrUpdateUser({
    externalId: machineId,
  });

  const wallet = await dynamicClient.wallets.createEmbeddedWallet(user.id);

  console.log(JSON.stringify({
    address: wallet.address,
    dynamic_id: user.id
  }));
}

initAgent().catch(err => {
  console.error(err);
  process.exit(1);
});
```

#### Rust Subprocess Call

`src/cli/sleeves/identity.rs`

```rust
use crate::cmd::CmdLineRunner;
use machine_uid; // Add to Cargo.toml for stable hardware ID

pub fn initialize_agent_identity() -> eyre::Result<()> {
    let machine_id = machine_uid::get()?;

    let output = CmdLineRunner::new("node")
        .arg("src/assets/agent-sandbox/dynamic_init.mjs")
        .arg(machine_id)
        .env("DYNAMIC_ENVIRONMENT_ID", "your-id-here")
        .execute()?;

    // Parse output and store the 0x address in ~/.sleeve/agent.toml
    Ok(())
}
```

---

### 4.2 Solidity Escrow Contract (Circle Settlement)

Deployed on Base Sepolia. Allows Stakers to lock USDC against a specific Context Payload hash.

`BountyNetEscrow.sol`

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

contract BountyNetEscrow {
    address public oracle; // CI Oracle (Webhook Verifier) address
    IERC20 public usdc;

    struct Bounty {
        address creator;
        uint256 amount;
        bool resolved;
    }

    // Context Payload Hash -> Bounty Data
    mapping(bytes32 => Bounty) public bounties;

    constructor(address _oracle, address _usdc) {
        oracle = _oracle;
        usdc = IERC20(_usdc);
    }

    /// @notice Staker locks USDC against a specific Context Payload hash
    /// @dev Targets Circle bounty for Agentic Nanopayments
    function createBounty(bytes32 contextHash, uint256 amount) external {
        require(usdc.transferFrom(msg.sender, address(this), amount), "Transfer failed");
        bounties[contextHash] = Bounty(msg.sender, amount, false);
    }

    /// @notice Called by the CI Oracle once the Solver's PR passes CI
    function resolveBounty(bytes32 contextHash, address solver) external {
        require(msg.sender == oracle, "Only oracle can resolve");
        Bounty storage b = bounties[contextHash];
        require(!b.resolved, "Already resolved");
        require(b.amount > 0, "No bounty found");

        b.resolved = true;

        // Payout: 70% to Solver, 30% to Paymaster (reloads Compute Credits)
        uint256 solverShare = (b.amount * 70) / 100;
        uint256 paymasterShare = b.amount - solverShare;

        usdc.transfer(solver, solverShare);
        usdc.transfer(oracle, paymasterShare);
    }
}
```

---

## 5. Pricing & Barter Economics

### 5.1 Outcome-First Valuation

The fundamental unit of value is the **Green CI State**.

- **Staker perspective:** Payment is for the removal of a deployment blocker, not for "10 minutes of debugging." Price reflects the opportunity cost of the broken CI.
- **Solver perspective:** The agent calculates its Marginal Cost of Inference. With surplus Compute Credits from prior tasks, cost approaches zero — making it highly competitive.

### 5.2 Barter Exchange Rate — Resource Oracle

A lightweight Resource Price Oracle inside `sleeve` monitors market floor pricing for major providers. All resources are denominated against a common unit.

| Resource  | Market Floor (Proxy Unit) | 1.00 USDC Equivalent |
|-----------|--------------------------|----------------------|
| Inference | 1,000 Sonnet 3.5 Tokens  | ~1.5 units           |
| Storage   | 10GB S3-IA (24 hrs)      | ~0.8 units           |
| Compute   | 1 hr AWS t3.medium       | ~2.0 units           |

When a Staker offers an S3 bucket, the smart contract holds a Resource Claim valued at the current oracle price. If 10GB of storage equals 5,000 tokens, the Solver accepts the barter because the value matches its current needs.

### 5.3 Progressive Bounty Escalation

If a bounty remains unsolved, the Context Layer can autonomously increase the reward.

| Phase     | Trigger                    | Action                                          |
|-----------|----------------------------|-------------------------------------------------|
| Dampening | Bounty created             | Starts at 1.00 USDC                            |
| Interest  | No pickup after 1 hour     | Adds Resource Modifier (e.g., +1 hr GPU time) |
| High-Tier | Complex logic bug detected | Attracts Solvers requiring more expensive models|

This ensures code eventually gets fixed without human intervention.

---

## 6. Sleeve CLI UI

Extend `src/ui/mod.rs` to add a Bounty Dashboard pulling data from both Dynamic and Circle.

```
[Sleeve BountyNet Status]
ID: 0x82... (Agent Identity)
Network: Base Sepolia / Circle Arc

BALANCE & FUEL
USDC: 12.50
Compute Credits: 8,400 Tokens (Claude 3.5 Sonnet) [||||||----] 84%

ACTIVE LEASES (WON VIA BARTER)
- S3-Bucket-01: 50GB (Expires in 14h)
- Redis-Cache-BETA: 2GB (Active)

CURRENT INTENT
Monitoring: maceip/sleeve for CI failures...
```

**Dashboard fields:**

| Field           | Source  | Description                        |
|-----------------|---------|------------------------------------|
| Compute Credits | Circle  | Earned inference credits remaining |
| Active Leases   | Circle  | Resource Claims currently in use   |
| Reputation Score| Onchain | Count of verified bounties solved  |

---

## 7. Stack Summary

| Component           | Technology              | Purpose                                           |
|---------------------|-------------------------|---------------------------------------------------|
| Escrow Contract     | Solidity (Base Sepolia) | Holds USDC and Resource Claim NFTs                |
| Solver Agent        | Python (Wake)           | Ingests Context Payload, generates patches        |
| Inference Proxy     | Node/Express            | Wraps Anthropic; bills against Staked Credits     |
| CI Oracle           | Node.js                 | Listens to GitHub Webhooks to trigger payouts     |
| Sleeve CLI          | Rust                    | Orchestrates local env and proxies Compute Credits|
| Headless Onboarding | Dynamic Node SDK        | Mints Agent Identities for bystanders             |
| Bounty Feed         | Web/Mobile App          | Marketplace UI for active Context Payloads        |
| SimBountyNet        | TBD                     | Simulated Stakers/Solvers for demo activity       |

---

## 8. Repo Notes

- `sleeve` was recently forked from the Rust `mise` project (`maceip/sleeve` or `maceip/sleeves`).
- For the hackathon: create fresh git repos, then apply the pattern: **fork mise → apply existing commits on top of mise → apply everything in this spec**.
